DROP TABLE IF EXISTS Person;
DROP TABLE IF EXISTS Item;

CREATE TABLE Person (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL UNIQUE,
  phone INTEGER NULL
);

CREATE TABLE Item (
  personId INTEGER,
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title VARCHAR(255) NOT NULL,
  -- picture
  description TEXT NOT NULL,
  CONSTRAINT personIdConstraint FOREIGN KEY (personId) REFERENCES Person(id)
);

DESCRIBE Person;
DESCRIBE Item;
